events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            include       fastcgi_params;
            fastcgi_pass  127.0.0.1:8080;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param QUERY_STRING    $query_string;
        }

        location /status {
            stub_status;
        }
    }
}